version: '3.7'

services:
  api_tt:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api_tt
    hostname: api_tt
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - db_postgres
      - rabbitmq_tt
    volumes:
      - $PWD:/home

  db_postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db_postgres
    hostname: db_postgres
    ports:
      - '5432:5432'
    networks:
      - backend

  rabbitmq_tt:
    container_name: rabbitmq_tt
    hostname: rabbitmq_tt
    restart: always
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
    networks:
      - backend

  redis_tt:
      build:
        context: .
        dockerfile: docker/redis/Dockerfile
      container_name: redis_tt
      hostname: redis_tt
      ports:
        - '6377:6379'
      networks:
        - backend

networks:
  backend:
    driver: 'bridge'